### ISSUE TITLE
Some problems Helping 

### ISSUE THREAD

**Issue by CHMILYcs** [anushkadhiman/ObjectTracking-DeepSORT-YOLOv3-TF2#3]
Traceback (most recent call last):
  File "E:/ObjectTracking/object_tracker.py", line 140, in <module>
    Object_tracking(yolo, video_path, "track.mp4", input_size=YOLO_INPUT_SIZE, show=False, iou_threshold=0.1, rectangle_colors=(255,0,0), Track_only = ["person"],encoding='utf-8')
  File "E:/ObjectTracking/object_tracker.py", line 24, in Object_tracking
    encoder = gdet.create_box_encoder(model_filename, batch_size=1)
  File "E:\ObjectTracking\deep_sort\generate_detections.py", line 104, in create_box_encoder
    image_encoder = ImageEncoder(model_filename, input_name, output_name)
  File "E:\ObjectTracking\deep_sort\generate_detections.py", line 80, in __init__
    graph_def.ParseFromString(file_handle.read())
  File "D:\Python\Python38\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 116, in read
    self._preread_check()
  File "D:\Python\Python38\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 78, in _preread_check
    self._read_buf = _pywrap_file_io.BufferedInputStream(
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd5 in position 77: invalid continuation byte

**Comment by anushkadhiman** [comment]
It seems the error must be in passing video path. Please check the video path once. 
Not sure if it will help you, but it would be nice if it works.
